from PyQt6 import QtCore, QtGui, QtWidgets


class UiControlForm:
    def setup_ui(self, control_form):
        control_form.setObjectName("ControlForm")
        control_form.resize(675, 805)
        font = QtGui.QFont()
        control_form.setFont(font)
        self.widget = QtWidgets.QWidget(control_form)
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.grpJog = QtWidgets.QGroupBox(self.widget)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.grpJog.sizePolicy().hasHeightForWidth())
        self.grpJog.setSizePolicy(size_policy)
        self.grpJog.setObjectName("grpJog")
        self.gridLayout = QtWidgets.QGridLayout(self.grpJog)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spnJogMotor = QtWidgets.QSpinBox(self.grpJog)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.spnJogMotor.sizePolicy().hasHeightForWidth())
        self.spnJogMotor.setSizePolicy(size_policy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.spnJogMotor.setFont(font)
        self.spnJogMotor.setMinimum(1)
        self.spnJogMotor.setMaximum(32)
        self.spnJogMotor.setObjectName("spnJogMotor")
        self.horizontalLayout.addWidget(self.spnJogMotor)
        self.btnJogNeg = QtWidgets.QPushButton(self.grpJog)
        self.btnJogNeg.setEnabled(False)
        self.btnJogNeg.setObjectName("btnJogNeg")
        self.horizontalLayout.addWidget(self.btnJogNeg)
        self.btnHome = QtWidgets.QPushButton(self.grpJog)
        self.btnHome.setEnabled(False)
        self.btnHome.setObjectName("btnHome")
        self.horizontalLayout.addWidget(self.btnHome)
        self.btnJogPos = QtWidgets.QPushButton(self.grpJog)
        self.btnJogPos.setEnabled(False)
        self.btnJogPos.setObjectName("btnJogPos")
        self.horizontalLayout.addWidget(self.btnJogPos)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 4)
        self.textLabel5 = QtWidgets.QLabel(self.grpJog)
        self.textLabel5.setWordWrap(False)
        self.textLabel5.setObjectName("textLabel5")
        self.gridLayout.addWidget(self.textLabel5, 1, 0, 1, 1)
        self.textLabel4_2 = QtWidgets.QLabel(self.grpJog)
        self.textLabel4_2.setWordWrap(False)
        self.textLabel4_2.setObjectName("textLabel4_2")
        self.gridLayout.addWidget(self.textLabel4_2, 2, 2, 1, 1)
        self.btnJogTo = QtWidgets.QPushButton(self.grpJog)
        self.btnJogTo.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(29, 95, 19))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(29, 95, 19))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(115, 115, 115))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        self.btnJogTo.setPalette(palette)
        self.btnJogTo.setObjectName("btnJogTo")
        self.gridLayout.addWidget(self.btnJogTo, 2, 3, 1, 1)
        self.textLabel6 = QtWidgets.QLabel(self.grpJog)
        self.textLabel6.setWordWrap(False)
        self.textLabel6.setObjectName("textLabel6")
        self.gridLayout.addWidget(self.textLabel6, 3, 0, 1, 1)
        self.lblPosition = QtWidgets.QLabel(self.grpJog)
        self.lblPosition.setMinimumSize(QtCore.QSize(0, 28))
        self.lblPosition.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lblPosition.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lblPosition.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.lblPosition.setWordWrap(False)
        self.lblPosition.setObjectName("lblPosition")
        self.gridLayout.addWidget(self.lblPosition, 3, 1, 1, 1)
        self.textLabel4_2_2 = QtWidgets.QLabel(self.grpJog)
        self.textLabel4_2_2.setWordWrap(False)
        self.textLabel4_2_2.setObjectName("textLabel4_2_2")
        self.gridLayout.addWidget(self.textLabel4_2_2, 3, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pixHiLim = QtWidgets.QLabel(self.grpJog)
        self.pixHiLim.setMaximumSize(QtCore.QSize(25, 25))
        self.pixHiLim.setPixmap(QtGui.QPixmap("redLedOff.png"))
        self.pixHiLim.setWordWrap(False)
        self.pixHiLim.setObjectName("pixHiLim")
        self.horizontalLayout_2.addWidget(self.pixHiLim)
        self.lblHiLim = QtWidgets.QLabel(self.grpJog)
        self.lblHiLim.setWordWrap(False)
        self.lblHiLim.setObjectName("lblHiLim")
        self.horizontalLayout_2.addWidget(self.lblHiLim)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 3, 1, 1)
        self.textLabel7 = QtWidgets.QLabel(self.grpJog)
        self.textLabel7.setWordWrap(False)
        self.textLabel7.setObjectName("textLabel7")
        self.gridLayout.addWidget(self.textLabel7, 4, 0, 1, 1)
        self.lblVelo = QtWidgets.QLabel(self.grpJog)
        self.lblVelo.setMinimumSize(QtCore.QSize(0, 28))
        self.lblVelo.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lblVelo.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lblVelo.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.lblVelo.setWordWrap(False)
        self.lblVelo.setObjectName("lblVelo")
        self.gridLayout.addWidget(self.lblVelo, 4, 1, 1, 1)
        self.textLabel4_2_2_2 = QtWidgets.QLabel(self.grpJog)
        self.textLabel4_2_2_2.setWordWrap(False)
        self.textLabel4_2_2_2.setObjectName("textLabel4_2_2_2")
        self.gridLayout.addWidget(self.textLabel4_2_2_2, 4, 2, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pixLoLim = QtWidgets.QLabel(self.grpJog)
        self.pixLoLim.setMaximumSize(QtCore.QSize(20, 20))
        self.pixLoLim.setPixmap(QtGui.QPixmap("redLedOff.png"))
        self.pixLoLim.setWordWrap(False)
        self.pixLoLim.setObjectName("pixLoLim")
        self.horizontalLayout_3.addWidget(self.pixLoLim)
        self.lblLoLim = QtWidgets.QLabel(self.grpJog)
        self.lblLoLim.setWordWrap(False)
        self.lblLoLim.setObjectName("lblLoLim")
        self.horizontalLayout_3.addWidget(self.lblLoLim)
        self.gridLayout.addLayout(self.horizontalLayout_3, 4, 3, 1, 1)
        self.textLabel8 = QtWidgets.QLabel(self.grpJog)
        self.textLabel8.setWordWrap(False)
        self.textLabel8.setObjectName("textLabel8")
        self.gridLayout.addWidget(self.textLabel8, 5, 0, 1, 1)
        self.lblFolErr = QtWidgets.QLabel(self.grpJog)
        self.lblFolErr.setMinimumSize(QtCore.QSize(0, 28))
        self.lblFolErr.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lblFolErr.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lblFolErr.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignRight
            | QtCore.Qt.AlignmentFlag.AlignTrailing
            | QtCore.Qt.AlignmentFlag.AlignVCenter
        )
        self.lblFolErr.setWordWrap(False)
        self.lblFolErr.setObjectName("lblFolErr")
        self.gridLayout.addWidget(self.lblFolErr, 5, 1, 1, 1)
        self.textLabel4_2_2_3 = QtWidgets.QLabel(self.grpJog)
        self.textLabel4_2_2_3.setWordWrap(False)
        self.textLabel4_2_2_3.setObjectName("textLabel4_2_2_3")
        self.gridLayout.addWidget(self.textLabel4_2_2_3, 5, 2, 1, 1)
        self.btnStatus = QtWidgets.QPushButton(self.grpJog)
        self.btnStatus.setEnabled(False)
        self.btnStatus.setObjectName("btnStatus")
        self.gridLayout.addWidget(self.btnStatus, 6, 0, 1, 1)
        self.btnSettings = QtWidgets.QPushButton(self.grpJog)
        self.btnSettings.setEnabled(False)
        self.btnSettings.setObjectName("btnSettings")
        self.gridLayout.addWidget(self.btnSettings, 6, 1, 1, 2)
        self.btnJogStop = QtWidgets.QPushButton(self.grpJog)
        self.btnJogStop.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(232, 0, 3))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(232, 0, 3))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(115, 115, 115))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        self.btnJogStop.setPalette(palette)
        self.btnJogStop.setObjectName("btnJogStop")
        self.gridLayout.addWidget(self.btnJogStop, 5, 3, 1, 1)
        self.lneJogDist = QtWidgets.QLineEdit(self.grpJog)
        self.lneJogDist.setEnabled(False)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lneJogDist.sizePolicy().hasHeightForWidth())
        self.lneJogDist.setSizePolicy(size_policy)
        self.lneJogDist.setMinimumSize(QtCore.QSize(0, 28))
        self.lneJogDist.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.lneJogDist.setObjectName("lneJogDist")
        self.gridLayout.addWidget(self.lneJogDist, 1, 1, 1, 1)
        self.textLabel4 = QtWidgets.QLabel(self.grpJog)
        self.textLabel4.setWordWrap(False)
        self.textLabel4.setObjectName("textLabel4")
        self.gridLayout.addWidget(self.textLabel4, 1, 2, 1, 1)
        self.chkJogInc = QtWidgets.QCheckBox(self.grpJog)
        self.chkJogInc.setEnabled(False)
        self.chkJogInc.setChecked(True)
        self.chkJogInc.setObjectName("chkJogInc")
        self.gridLayout.addWidget(self.chkJogInc, 1, 3, 1, 1)
        self.textLabel3 = QtWidgets.QLabel(self.grpJog)
        self.textLabel3.setWordWrap(False)
        self.textLabel3.setObjectName("textLabel3")
        self.gridLayout.addWidget(self.textLabel3, 2, 0, 1, 1)
        self.lneJogTo = QtWidgets.QLineEdit(self.grpJog)
        self.lneJogTo.setEnabled(False)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lneJogTo.sizePolicy().hasHeightForWidth())
        self.lneJogTo.setSizePolicy(size_policy)
        self.lneJogTo.setMinimumSize(QtCore.QSize(0, 28))
        self.lneJogTo.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight)
        self.lneJogTo.setObjectName("lneJogTo")
        self.gridLayout.addWidget(self.lneJogTo, 2, 1, 1, 1)
        self.btnKillMotor = QtWidgets.QPushButton(self.grpJog)
        self.btnKillMotor.setEnabled(False)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(232, 0, 3))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(232, 0, 3))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(115, 115, 115))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        self.btnKillMotor.setPalette(palette)
        self.btnKillMotor.setObjectName("btnKillMotor")
        self.gridLayout.addWidget(self.btnKillMotor, 6, 3, 1, 1)
        self.gridLayout_2.addWidget(self.grpJog, 0, 1, 1, 1)
        self.groupBox1 = QtWidgets.QGroupBox(self.widget)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.groupBox1.sizePolicy().hasHeightForWidth())
        self.groupBox1.setSizePolicy(size_policy)
        self.groupBox1.setAlignment(
            QtCore.Qt.AlignmentFlag.AlignLeading
            | QtCore.Qt.AlignmentFlag.AlignLeft
            | QtCore.Qt.AlignmentFlag.AlignTop
        )
        self.groupBox1.setObjectName("groupBox1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox1)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnGroupProtocol = QtWidgets.QGroupBox(self.groupBox1)
        self.btnGroupProtocol.setMinimumSize(QtCore.QSize(100, 0))
        self.btnGroupProtocol.setObjectName("btnGroupProtocol")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.btnGroupProtocol)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.rbUseTerminalServer = QtWidgets.QRadioButton(self.btnGroupProtocol)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(
            self.rbUseTerminalServer.sizePolicy().hasHeightForWidth()
        )
        self.rbUseTerminalServer.setSizePolicy(size_policy)
        self.rbUseTerminalServer.setChecked(False)
        self.rbUseTerminalServer.setObjectName("rbUseTerminalServer")
        self.gridLayout_3.addWidget(self.rbUseTerminalServer, 0, 0, 1, 1)
        self.rbUseSocket = QtWidgets.QRadioButton(self.btnGroupProtocol)
        self.rbUseSocket.setEnabled(True)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.rbUseSocket.sizePolicy().hasHeightForWidth())
        self.rbUseSocket.setSizePolicy(size_policy)
        self.rbUseSocket.setObjectName("rbUseSocket")
        self.gridLayout_3.addWidget(self.rbUseSocket, 1, 0, 1, 1)
        self.rbUseSerial = QtWidgets.QRadioButton(self.btnGroupProtocol)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.rbUseSerial.sizePolicy().hasHeightForWidth())
        self.rbUseSerial.setSizePolicy(size_policy)
        self.rbUseSerial.setChecked(True)
        self.rbUseSerial.setObjectName("rbUseSerial")
        self.gridLayout_3.addWidget(self.rbUseSerial, 2, 0, 1, 1)
        self.rbUseSsh = QtWidgets.QRadioButton(self.btnGroupProtocol)
        self.rbUseSsh.setEnabled(True)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.rbUseSsh.sizePolicy().hasHeightForWidth())
        self.rbUseSsh.setSizePolicy(size_policy)
        self.rbUseSsh.setObjectName("rbUseSsh")
        self.gridLayout_3.addWidget(self.rbUseSsh, 3, 0, 1, 1)
        self.verticalLayout.addWidget(self.btnGroupProtocol)
        self.gridlayout = QtWidgets.QGridLayout()
        self.gridlayout.setSpacing(6)
        self.gridlayout.setObjectName("gridlayout")
        self.textLabel1 = QtWidgets.QLabel(self.groupBox1)
        self.textLabel1.setMinimumSize(QtCore.QSize(75, 27))
        self.textLabel1.setMaximumSize(QtCore.QSize(75, 25))
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.gridlayout.addWidget(self.textLabel1, 0, 0, 1, 1)
        self.lneServer = QtWidgets.QLineEdit(self.groupBox1)
        self.lneServer.setObjectName("lneServer")
        self.gridlayout.addWidget(self.lneServer, 0, 1, 1, 1)
        self.textLabel2 = QtWidgets.QLabel(self.groupBox1)
        self.textLabel2.setMinimumSize(QtCore.QSize(75, 27))
        self.textLabel2.setMaximumSize(QtCore.QSize(75, 27))
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName("textLabel2")
        self.gridlayout.addWidget(self.textLabel2, 1, 0, 1, 1)
        self.lnePort = QtWidgets.QLineEdit(self.groupBox1)
        self.lnePort.setObjectName("lnePort")
        self.gridlayout.addWidget(self.lnePort, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridlayout)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setSpacing(6)
        self.hboxlayout.setObjectName("hboxlayout")
        self.btnConnect = QtWidgets.QPushButton(self.groupBox1)
        self.btnConnect.setObjectName("btnConnect")
        self.hboxlayout.addWidget(self.btnConnect)
        self.btnDisconnect = QtWidgets.QPushButton(self.groupBox1)
        self.btnDisconnect.setEnabled(False)
        self.btnDisconnect.setObjectName("btnDisconnect")
        self.hboxlayout.addWidget(self.btnDisconnect)
        self.verticalLayout.addLayout(self.hboxlayout)
        self.gridLayout_2.addWidget(self.groupBox1, 0, 0, 1, 1)
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setSpacing(6)
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.lneSend = QtWidgets.QLineEdit(self.widget)
        self.lneSend.setEnabled(False)
        self.lneSend.setObjectName("lneSend")
        self.hboxlayout1.addWidget(self.lneSend)
        self.btnSend = QtWidgets.QPushButton(self.widget)
        self.btnSend.setEnabled(False)
        self.btnSend.setObjectName("btnSend")
        self.hboxlayout1.addWidget(self.btnSend)
        self.chkShowAll = QtWidgets.QCheckBox(self.widget)
        self.chkShowAll.setObjectName("chkShowAll")
        self.hboxlayout1.addWidget(self.chkShowAll)
        self.gridLayout_2.addLayout(self.hboxlayout1, 7, 0, 1, 2)
        self.frame3 = QtWidgets.QFrame(self.widget)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.frame3.sizePolicy().hasHeightForWidth())
        self.frame3.setSizePolicy(size_policy)
        self.frame3.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.frame3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.frame3.setObjectName("frame3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame3)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btnEnergise = QtWidgets.QPushButton(self.frame3)
        self.btnEnergise.setEnabled(False)
        self.btnEnergise.setObjectName("btnEnergise")
        self.gridLayout_4.addWidget(self.btnEnergise, 2, 5, 1, 1)
        self.btnCSStatus = QtWidgets.QPushButton(self.frame3)
        self.btnCSStatus.setEnabled(False)
        self.btnCSStatus.setObjectName("btnCSStatus")
        self.gridLayout_4.addWidget(self.btnCSStatus, 0, 6, 1, 1)
        self.lblPolling = QtWidgets.QLabel(self.frame3)
        self.lblPolling.setMaximumSize(QtCore.QSize(65, 27))
        self.lblPolling.setWordWrap(False)
        self.lblPolling.setObjectName("lblPolling")
        self.gridLayout_4.addWidget(self.lblPolling, 2, 1, 1, 1)
        self.lnePollRate = QtWidgets.QLineEdit(self.frame3)
        self.lnePollRate.setEnabled(False)
        self.lnePollRate.setMaximumSize(QtCore.QSize(40, 27))
        self.lnePollRate.setObjectName("lnePollRate")
        self.gridLayout_4.addWidget(self.lnePollRate, 2, 2, 1, 1)
        self.pixPolling = QtWidgets.QLabel(self.frame3)
        self.pixPolling.setMaximumSize(QtCore.QSize(25, 25))
        self.pixPolling.setPixmap(QtGui.QPixmap("greenLedOff.png"))
        self.pixPolling.setWordWrap(False)
        self.pixPolling.setObjectName("pixPolling")
        self.gridLayout_4.addWidget(self.pixPolling, 2, 0, 1, 1)
        self.lblPollRate = QtWidgets.QLabel(self.frame3)
        self.lblPollRate.setEnabled(False)
        self.lblPollRate.setObjectName("lblPollRate")
        self.gridLayout_4.addWidget(self.lblPollRate, 2, 3, 1, 1)
        self.btnGlobalStatus = QtWidgets.QPushButton(self.frame3)
        self.btnGlobalStatus.setEnabled(False)
        self.btnGlobalStatus.setObjectName("btnGlobalStatus")
        self.gridLayout_4.addWidget(self.btnGlobalStatus, 2, 6, 1, 1)
        self.btnKillAll = QtWidgets.QPushButton(self.frame3)
        self.btnKillAll.setEnabled(False)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.btnKillAll.sizePolicy().hasHeightForWidth())
        self.btnKillAll.setSizePolicy(size_policy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(232, 0, 3))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush
        )
        brush = QtGui.QBrush(QtGui.QColor(232, 0, 3))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(115, 115, 115))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        self.btnKillAll.setPalette(palette)
        self.btnKillAll.setObjectName("btnKillAll")
        self.gridLayout_4.addWidget(self.btnKillAll, 2, 7, 1, 1)
        self.btnLoadFile = QtWidgets.QPushButton(self.frame3)
        self.btnLoadFile.setEnabled(False)
        self.btnLoadFile.setObjectName("btnLoadFile")
        self.gridLayout_4.addWidget(self.btnLoadFile, 0, 7, 1, 1)
        self.btnPollingStatus = QtWidgets.QPushButton(self.frame3)
        self.btnPollingStatus.setEnabled(False)
        self.btnPollingStatus.setCheckable(False)
        self.btnPollingStatus.setObjectName("btnPollingStatus")
        self.gridLayout_4.addWidget(self.btnPollingStatus, 0, 0, 1, 4)
        self.btnGather = QtWidgets.QPushButton(self.frame3)
        self.btnGather.setEnabled(False)
        self.btnGather.setObjectName("btnGather")
        self.gridLayout_4.addWidget(self.btnGather, 0, 5, 1, 1)
        self.btnWatches = QtWidgets.QPushButton(self.frame3)
        self.btnWatches.setEnabled(False)
        self.btnWatches.setObjectName("btnWatches")
        self.gridLayout_4.addWidget(self.btnWatches, 2, 4, 1, 1)
        self.gridLayout_2.addWidget(self.frame3, 5, 0, 1, 2)
        self.splitter = QtWidgets.QSplitter(self.widget)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(size_policy)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.table = QtWidgets.QTableWidget(self.splitter)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        size_policy.setHorizontalStretch(1)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(size_policy)
        self.table.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.table.setFont(font)
        self.table.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents
        )
        self.table.setSelectionMode(
            QtWidgets.QAbstractItemView.SelectionMode.NoSelection
        )
        self.table.setProperty("dragAutoScroll", False)
        self.table.setProperty("numRows", 32)
        self.table.setProperty("numCols", 5)
        self.table.setProperty("rowMovingEnabled", False)
        self.table.setProperty("columnMovingEnabled", False)
        self.table.setProperty("readOnly", True)
        self.table.setObjectName("table")
        self.table.setColumnCount(7)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setDefaultSectionSize(94)
        self.table.horizontalHeader().setMinimumSectionSize(50)
        self.table.verticalHeader().setDefaultSectionSize(20)
        self.txtShell = QtWidgets.QTextEdit(self.splitter)
        self.txtShell.setEnabled(True)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        size_policy.setHorizontalStretch(1)
        size_policy.setVerticalStretch(1)
        size_policy.setHeightForWidth(self.txtShell.sizePolicy().hasHeightForWidth())
        self.txtShell.setSizePolicy(size_policy)
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(9)
        self.txtShell.setFont(font)
        self.txtShell.setReadOnly(True)
        self.txtShell.setObjectName("txtShell")
        self.gridLayout_2.addWidget(self.splitter, 6, 0, 1, 2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lblIdentity = QtWidgets.QLabel(self.widget)
        size_policy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.MinimumExpanding,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        size_policy.setHorizontalStretch(0)
        size_policy.setVerticalStretch(0)
        size_policy.setHeightForWidth(self.lblIdentity.sizePolicy().hasHeightForWidth())
        self.lblIdentity.setSizePolicy(size_policy)
        self.lblIdentity.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lblIdentity.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.lblIdentity.setWordWrap(False)
        self.lblIdentity.setObjectName("lblIdentity")
        self.horizontalLayout_6.addWidget(self.lblIdentity)
        self.pixUnderVoltage = QtWidgets.QLabel(self.widget)
        self.pixUnderVoltage.setMaximumSize(QtCore.QSize(25, 25))
        self.pixUnderVoltage.setPixmap(QtGui.QPixmap("greenLedOff.png"))
        self.pixUnderVoltage.setWordWrap(False)
        self.pixUnderVoltage.setObjectName("pixUnderVoltage")
        self.horizontalLayout_6.addWidget(self.pixUnderVoltage)
        self.lblUnderVoltage = QtWidgets.QLabel(self.widget)
        self.lblUnderVoltage.setWordWrap(True)
        self.lblUnderVoltage.setObjectName("lblUnderVoltage")
        self.horizontalLayout_6.addWidget(self.lblUnderVoltage)
        self.pixOverVoltage = QtWidgets.QLabel(self.widget)
        self.pixOverVoltage.setMaximumSize(QtCore.QSize(25, 25))
        self.pixOverVoltage.setPixmap(QtGui.QPixmap("greenLedOff.png"))
        self.pixOverVoltage.setWordWrap(False)
        self.pixOverVoltage.setObjectName("pixOverVoltage")
        self.horizontalLayout_6.addWidget(self.pixOverVoltage)
        self.lblOverVoltage = QtWidgets.QLabel(self.widget)
        self.lblOverVoltage.setObjectName("lblOverVoltage")
        self.horizontalLayout_6.addWidget(self.lblOverVoltage)
        self.pixOverTemperature = QtWidgets.QLabel(self.widget)
        self.pixOverTemperature.setMaximumSize(QtCore.QSize(25, 25))
        self.pixOverTemperature.setPixmap(QtGui.QPixmap("greenLedOff.png"))
        self.pixOverTemperature.setWordWrap(False)
        self.pixOverTemperature.setObjectName("pixOverTemperature")
        self.horizontalLayout_6.addWidget(self.pixOverTemperature)
        self.lblOverTemperature = QtWidgets.QLabel(self.widget)
        self.lblOverTemperature.setObjectName("lblOverTemperature")
        self.horizontalLayout_6.addWidget(self.lblOverTemperature)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 3, 0, 1, 2)
        control_form.setCentralWidget(self.widget)

        self.retranslate_ui(control_form)
        self.spnJogMotor.valueChanged["int"].connect(control_form.jog_change_motor)
        self.btnJogPos.clicked.connect(control_form.jog_pos)
        self.btnSend.clicked.connect(control_form.send_single_command)
        self.lneSend.returnPressed.connect(control_form.send_single_command)
        self.lneJogTo.returnPressed.connect(control_form.jog_go_to_position)
        self.lneServer.returnPressed.connect(self.lnePort.selectAll)
        self.lneServer.returnPressed.connect(self.lnePort.setFocus)
        self.lnePort.returnPressed.connect(self.rbUseTerminalServer.setFocus)
        self.rbUseTerminalServer.clicked.connect(
            control_form.use_terminal_server_connection
        )
        self.rbUseSocket.clicked.connect(control_form.use_socket_connection)
        self.rbUseSsh.clicked.connect(control_form.use_ssh_connection)
        self.btnDisconnect.clicked.connect(control_form.remote_disconnect)
        self.btnConnect.clicked.connect(control_form.remote_connect)
        self.lnePort.returnPressed.connect(control_form.remote_connect)
        self.btnKillMotor.clicked.connect(control_form.kill_motor)
        self.chkJogInc.toggled["bool"].connect(control_form.jog_incrementally)
        self.btnJogStop.clicked.connect(control_form.jog_stop)
        self.btnJogTo.clicked.connect(control_form.jog_go_to_position)
        self.btnSettings.clicked.connect(control_form.jog_parameters)
        self.btnStatus.clicked.connect(control_form.status_screen)
        self.btnJogNeg.clicked.connect(control_form.jog_neg)
        self.table.cellDoubleClicked["int", "int"].connect(
            control_form.chooseMotorFromTable
        )
        self.btnGather.clicked.connect(control_form.data_gather)
        self.btnWatches.clicked.connect(control_form.watches)
        self.btnPollingStatus.clicked.connect(control_form.pmac_polling_status)
        self.btnLoadFile.clicked.connect(control_form.pmac_load_config)
        self.btnKillAll.clicked.connect(control_form.kill_all_motors)
        self.btnEnergise.clicked.connect(control_form.pmac_energise_axis)
        self.btnCSStatus.clicked.connect(control_form.cs_status_screen)
        self.btnGlobalStatus.clicked.connect(control_form.global_status_screen)
        self.btnHome.clicked.connect(control_form.jog_home)
        self.rbUseSerial.clicked.connect(control_form.use_serial)
        QtCore.QMetaObject.connectSlotsByName(control_form)
        control_form.setTabOrder(self.rbUseTerminalServer, self.rbUseSocket)
        control_form.setTabOrder(self.rbUseSocket, self.lneServer)
        control_form.setTabOrder(self.lneServer, self.lnePort)
        control_form.setTabOrder(self.lnePort, self.btnDisconnect)
        control_form.setTabOrder(self.btnDisconnect, self.lneSend)
        control_form.setTabOrder(self.lneSend, self.lneJogDist)
        control_form.setTabOrder(self.lneJogDist, self.btnJogNeg)
        control_form.setTabOrder(self.btnJogNeg, self.btnJogPos)
        control_form.setTabOrder(self.btnJogPos, self.lneJogTo)
        control_form.setTabOrder(self.lneJogTo, self.btnJogTo)
        control_form.setTabOrder(self.btnJogTo, self.btnLoadFile)
        control_form.setTabOrder(self.btnLoadFile, self.btnPollingStatus)
        control_form.setTabOrder(self.btnPollingStatus, self.btnGather)
        control_form.setTabOrder(self.btnGather, self.chkJogInc)
        control_form.setTabOrder(self.chkJogInc, self.btnSend)
        control_form.setTabOrder(self.btnSend, self.txtShell)
        control_form.setTabOrder(self.txtShell, self.btnStatus)
        control_form.setTabOrder(self.btnStatus, self.btnSettings)
        control_form.setTabOrder(self.btnSettings, self.btnHome)
        control_form.setTabOrder(self.btnHome, self.btnGlobalStatus)
        control_form.setTabOrder(self.btnGlobalStatus, self.btnCSStatus)
        control_form.setTabOrder(self.btnCSStatus, self.btnEnergise)
        control_form.setTabOrder(self.btnEnergise, self.spnJogMotor)
        control_form.setTabOrder(self.spnJogMotor, self.btnKillMotor)
        control_form.setTabOrder(self.btnKillMotor, self.btnJogStop)
        control_form.setTabOrder(self.btnJogStop, self.table)
        control_form.setTabOrder(self.table, self.chkShowAll)

    def retranslate_ui(self, control_form):
        _translate = QtCore.QCoreApplication.translate
        control_form.setWindowTitle(
            _translate("ControlForm", "Delta Tau motor controller")
        )
        self.grpJog.setTitle(_translate("ControlForm", "Jog ribbon"))
        self.spnJogMotor.setToolTip(
            _translate("ControlForm", "Choose the motor to jog")
        )
        self.btnJogNeg.setText(_translate("ControlForm", "jog neg"))
        self.btnHome.setText(_translate("ControlForm", "home"))
        self.btnJogPos.setText(_translate("ControlForm", "jog pos"))
        self.textLabel5.setText(_translate("ControlForm", "distance:"))
        self.textLabel4_2.setText(_translate("ControlForm", "cts"))
        self.btnJogTo.setToolTip(_translate("ControlForm", "Jog to position"))
        self.btnJogTo.setText(_translate("ControlForm", "go"))
        self.textLabel6.setText(_translate("ControlForm", "position:"))
        self.lblPosition.setText(_translate("ControlForm", "0"))
        self.textLabel4_2_2.setText(_translate("ControlForm", "cts"))
        self.lblHiLim.setText(_translate("ControlForm", "HI limit"))
        self.textLabel7.setText(_translate("ControlForm", "velocity:"))
        self.lblVelo.setText(_translate("ControlForm", "0"))
        self.textLabel4_2_2_2.setText(_translate("ControlForm", "cts/s"))
        self.lblLoLim.setText(_translate("ControlForm", "LO limit"))
        self.textLabel8.setText(_translate("ControlForm", "fol. error:"))
        self.lblFolErr.setText(_translate("ControlForm", "0"))
        self.textLabel4_2_2_3.setText(_translate("ControlForm", "cts"))
        self.btnStatus.setText(_translate("ControlForm", "status..."))
        self.btnSettings.setText(_translate("ControlForm", "settings..."))
        self.btnJogStop.setText(_translate("ControlForm", "stop"))
        self.lneJogDist.setText(_translate("ControlForm", "1000"))
        self.textLabel4.setText(_translate("ControlForm", "cts"))
        self.chkJogInc.setText(_translate("ControlForm", "jog incr"))
        self.textLabel3.setText(_translate("ControlForm", "jog to:"))
        self.lneJogTo.setText(_translate("ControlForm", "0"))
        self.btnKillMotor.setText(_translate("ControlForm", "kill motor"))
        self.groupBox1.setTitle(_translate("ControlForm", "Connection to PMAC"))
        self.btnGroupProtocol.setTitle(_translate("ControlForm", "Protocol"))
        self.rbUseTerminalServer.setText(_translate("ControlForm", "Terminal Server"))
        self.rbUseSocket.setText(_translate("ControlForm", "TCP/IP Ethernet"))
        self.rbUseSerial.setText(_translate("ControlForm", "RS232 Serial"))
        self.rbUseSsh.setText(_translate("ControlForm", "SSH"))
        self.textLabel1.setText(_translate("ControlForm", "server:"))
        self.textLabel2.setText(_translate("ControlForm", "port:"))
        self.btnConnect.setText(_translate("ControlForm", "connect"))
        self.btnDisconnect.setText(_translate("ControlForm", "disconnect"))
        self.btnSend.setText(_translate("ControlForm", "send"))
        self.chkShowAll.setText(_translate("ControlForm", "show all commands sent"))
        self.btnEnergise.setText(_translate("ControlForm", "energise..."))
        self.btnCSStatus.setText(_translate("ControlForm", "CS Status..."))
        self.lblPolling.setText(_translate("ControlForm", "Polling"))
        self.lblPollRate.setText(_translate("ControlForm", "Hz"))
        self.btnGlobalStatus.setText(_translate("ControlForm", "Global Status..."))
        self.btnKillAll.setToolTip(
            _translate(
                "ControlForm",
                "Kill All (CTRL-K) motion by opening servo loops and setting zero velocity",
            )
        )
        self.btnKillAll.setText(_translate("ControlForm", "KILL ALL!"))
        self.btnLoadFile.setText(_translate("ControlForm", "load pmc..."))
        self.btnPollingStatus.setText(_translate("ControlForm", "disable polling"))
        self.btnGather.setText(_translate("ControlForm", "gather..."))
        self.btnWatches.setText(_translate("ControlForm", "watches..."))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("ControlForm", "position"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("ControlForm", "velocity"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("ControlForm", "foll. error"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("ControlForm", "hi lim"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("ControlForm", "lo lim"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("ControlForm", "i2t fault"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("ControlForm", "over current"))
        self.txtShell.setHtml(
            _translate(
                "ControlForm",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'Courier'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                '<table border="0" style="-qt-table-type: root; margin-top:4px; margin-bottom:4px; margin-left:4px; margin-right:4px;">\n'
                "<tr>\n"
                '<td style="border: none;">\n'
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:10pt;"><br /></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:10pt;"><br /></span></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;"><br /></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:8pt;"><br /></span></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;"><br /></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:8pt;"><br /></span></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;"><br /></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:8pt;"><br /></span></p>\n'
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;"><br /></p>\n'
                '<p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-size:8pt;"><br /></span></p></td></tr></table></body></html>',
            )
        )
        self.lblIdentity.setText(_translate("ControlForm", "Test"))
        self.lblUnderVoltage.setText(_translate("ControlForm", "Under Voltage"))
        self.lblOverVoltage.setText(_translate("ControlForm", "Over Voltage"))
        self.lblOverTemperature.setText(_translate("ControlForm", "Over Temperature"))
