# Form implementation generated from reading ui file 'dls_pmac_control/formLogin.ui'
#
# Created by: PyQt6 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets


class UiLogin:
    def setup_ui(self, login):
        login.setObjectName("Login")
        login.resize(314, 145)
        self.layoutWidget = QtWidgets.QWidget(login)
        self.layoutWidget.setGeometry(QtCore.QRect(51, 11, 215, 80))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelUsername = QtWidgets.QLabel(self.layoutWidget)
        self.labelUsername.setObjectName("labelUsername")
        self.gridLayout.addWidget(self.labelUsername, 0, 0, 1, 1)
        self.lneUsername = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneUsername.setText("")
        self.lneUsername.setObjectName("lneUsername")
        self.gridLayout.addWidget(self.lneUsername, 0, 1, 1, 1)
        self.labelPassword = QtWidgets.QLabel(self.layoutWidget)
        self.labelPassword.setObjectName("labelPassword")
        self.gridLayout.addWidget(self.labelPassword, 1, 0, 1, 1)
        self.lnePassword = QtWidgets.QLineEdit(self.layoutWidget)
        self.lnePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lnePassword.setObjectName("lnePassword")
        self.gridLayout.addWidget(self.lnePassword, 1, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(login)
        self.layoutWidget1.setGeometry(QtCore.QRect(65, 100, 184, 38))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.btnOK = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout.addWidget(self.btnOK)

        self.retranslate_ui(login)
        self.btnCancel.clicked.connect(login.clicked_cancel)
        self.btnOK.clicked.connect(login.clicked_ok)
        QtCore.QMetaObject.connectSlotsByName(login)
        login.setTabOrder(self.lneUsername, self.lnePassword)
        login.setTabOrder(self.lnePassword, self.btnOK)
        login.setTabOrder(self.btnOK, self.btnCancel)

    def retranslate_ui(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("Login", "SSH Login"))
        self.labelUsername.setText(_translate("Login", "Username:"))
        self.labelPassword.setText(_translate("Login", "Password:"))
        self.btnCancel.setText(_translate("Login", "Cancel"))
        self.btnOK.setText(_translate("Login", "OK"))
