# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dls_pmaccontrol/formWatches.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_formWatches(object):
    def setupUi(self, formWatches):
        formWatches.setObjectName("formWatches")
        formWatches.resize(905, 585)
        self.gridLayout_4 = QtWidgets.QGridLayout(formWatches)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.table = QtWidgets.QTableWidget(formWatches)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.table.setShowGrid(False)
        self.table.setProperty("numRows", 0)
        self.table.setProperty("numCols", 3)
        self.table.setObjectName("table")
        self.table.setColumnCount(3)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        self.gridLayout_4.addWidget(self.table, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox2 = QtWidgets.QGroupBox(formWatches)
        self.groupBox2.setObjectName("groupBox2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox2)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.textLabel1 = QtWidgets.QLabel(self.groupBox2)
        self.textLabel1.setWordWrap(False)
        self.textLabel1.setObjectName("textLabel1")
        self.gridLayout.addWidget(self.textLabel1, 0, 0, 1, 1)
        self.lneVariableName = QtWidgets.QLineEdit(self.groupBox2)
        self.lneVariableName.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lneVariableName.setText("")
        self.lneVariableName.setObjectName("lneVariableName")
        self.gridLayout.addWidget(self.lneVariableName, 0, 1, 1, 1)
        self.textLabel2 = QtWidgets.QLabel(self.groupBox2)
        self.textLabel2.setEnabled(False)
        self.textLabel2.setWordWrap(False)
        self.textLabel2.setObjectName("textLabel2")
        self.gridLayout.addWidget(self.textLabel2, 1, 0, 1, 1)
        self.lneMask = QtWidgets.QLineEdit(self.groupBox2)
        self.lneMask.setEnabled(False)
        self.lneMask.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lneMask.setObjectName("lneMask")
        self.gridLayout.addWidget(self.lneMask, 1, 1, 1, 1)
        self.btnAddWatch = QtWidgets.QPushButton(self.groupBox2)
        self.btnAddWatch.setAutoDefault(False)
        self.btnAddWatch.setObjectName("btnAddWatch")
        self.gridLayout.addWidget(self.btnAddWatch, 2, 0, 1, 2)
        self.verticalLayout.addWidget(self.groupBox2)
        self.btnRemoveWatch = QtWidgets.QPushButton(formWatches)
        self.btnRemoveWatch.setMouseTracking(True)
        self.btnRemoveWatch.setAutoDefault(False)
        self.btnRemoveWatch.setObjectName("btnRemoveWatch")
        self.verticalLayout.addWidget(self.btnRemoveWatch)
        self.btnClose = QtWidgets.QPushButton(formWatches)
        self.btnClose.setAutoDefault(False)
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout.addWidget(self.btnClose)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 1, 1, 1)
        self.panelEditWatch = QtWidgets.QGroupBox(formWatches)
        self.panelEditWatch.setEnabled(False)
        self.panelEditWatch.setObjectName("panelEditWatch")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.panelEditWatch)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.panelEditWatch)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cb15 = QtWidgets.QCheckBox(self.groupBox)
        self.cb15.setObjectName("cb15")
        self.gridLayout_2.addWidget(self.cb15, 0, 0, 1, 1)
        self.cb14 = QtWidgets.QCheckBox(self.groupBox)
        self.cb14.setObjectName("cb14")
        self.gridLayout_2.addWidget(self.cb14, 0, 1, 1, 1)
        self.cb13 = QtWidgets.QCheckBox(self.groupBox)
        self.cb13.setObjectName("cb13")
        self.gridLayout_2.addWidget(self.cb13, 0, 2, 1, 1)
        self.cb12 = QtWidgets.QCheckBox(self.groupBox)
        self.cb12.setObjectName("cb12")
        self.gridLayout_2.addWidget(self.cb12, 0, 3, 1, 1)
        self.cb11 = QtWidgets.QCheckBox(self.groupBox)
        self.cb11.setObjectName("cb11")
        self.gridLayout_2.addWidget(self.cb11, 0, 4, 1, 1)
        self.cb10 = QtWidgets.QCheckBox(self.groupBox)
        self.cb10.setObjectName("cb10")
        self.gridLayout_2.addWidget(self.cb10, 0, 5, 1, 1)
        self.cb9 = QtWidgets.QCheckBox(self.groupBox)
        self.cb9.setObjectName("cb9")
        self.gridLayout_2.addWidget(self.cb9, 0, 6, 1, 1)
        self.cb8 = QtWidgets.QCheckBox(self.groupBox)
        self.cb8.setObjectName("cb8")
        self.gridLayout_2.addWidget(self.cb8, 0, 7, 1, 1)
        self.cb7 = QtWidgets.QCheckBox(self.groupBox)
        self.cb7.setObjectName("cb7")
        self.gridLayout_2.addWidget(self.cb7, 0, 8, 1, 1)
        self.cb6 = QtWidgets.QCheckBox(self.groupBox)
        self.cb6.setObjectName("cb6")
        self.gridLayout_2.addWidget(self.cb6, 0, 9, 1, 1)
        self.cb5 = QtWidgets.QCheckBox(self.groupBox)
        self.cb5.setObjectName("cb5")
        self.gridLayout_2.addWidget(self.cb5, 0, 10, 1, 1)
        self.cb4 = QtWidgets.QCheckBox(self.groupBox)
        self.cb4.setObjectName("cb4")
        self.gridLayout_2.addWidget(self.cb4, 0, 11, 1, 1)
        self.cb3 = QtWidgets.QCheckBox(self.groupBox)
        self.cb3.setObjectName("cb3")
        self.gridLayout_2.addWidget(self.cb3, 0, 12, 1, 1)
        self.cb2 = QtWidgets.QCheckBox(self.groupBox)
        self.cb2.setObjectName("cb2")
        self.gridLayout_2.addWidget(self.cb2, 0, 13, 1, 1)
        self.cb1 = QtWidgets.QCheckBox(self.groupBox)
        self.cb1.setObjectName("cb1")
        self.gridLayout_2.addWidget(self.cb1, 0, 14, 1, 1)
        self.cb0 = QtWidgets.QCheckBox(self.groupBox)
        self.cb0.setObjectName("cb0")
        self.gridLayout_2.addWidget(self.cb0, 0, 15, 1, 1)
        self.cb31 = QtWidgets.QCheckBox(self.groupBox)
        self.cb31.setObjectName("cb31")
        self.gridLayout_2.addWidget(self.cb31, 1, 0, 1, 1)
        self.cb30 = QtWidgets.QCheckBox(self.groupBox)
        self.cb30.setObjectName("cb30")
        self.gridLayout_2.addWidget(self.cb30, 1, 1, 1, 1)
        self.cb29 = QtWidgets.QCheckBox(self.groupBox)
        self.cb29.setObjectName("cb29")
        self.gridLayout_2.addWidget(self.cb29, 1, 2, 1, 1)
        self.cb28 = QtWidgets.QCheckBox(self.groupBox)
        self.cb28.setObjectName("cb28")
        self.gridLayout_2.addWidget(self.cb28, 1, 3, 1, 1)
        self.cb27 = QtWidgets.QCheckBox(self.groupBox)
        self.cb27.setObjectName("cb27")
        self.gridLayout_2.addWidget(self.cb27, 1, 4, 1, 1)
        self.cb26 = QtWidgets.QCheckBox(self.groupBox)
        self.cb26.setObjectName("cb26")
        self.gridLayout_2.addWidget(self.cb26, 1, 5, 1, 1)
        self.cb25 = QtWidgets.QCheckBox(self.groupBox)
        self.cb25.setObjectName("cb25")
        self.gridLayout_2.addWidget(self.cb25, 1, 6, 1, 1)
        self.cb24 = QtWidgets.QCheckBox(self.groupBox)
        self.cb24.setObjectName("cb24")
        self.gridLayout_2.addWidget(self.cb24, 1, 7, 1, 1)
        self.cb23 = QtWidgets.QCheckBox(self.groupBox)
        self.cb23.setObjectName("cb23")
        self.gridLayout_2.addWidget(self.cb23, 1, 8, 1, 1)
        self.cb22 = QtWidgets.QCheckBox(self.groupBox)
        self.cb22.setObjectName("cb22")
        self.gridLayout_2.addWidget(self.cb22, 1, 9, 1, 1)
        self.cb21 = QtWidgets.QCheckBox(self.groupBox)
        self.cb21.setObjectName("cb21")
        self.gridLayout_2.addWidget(self.cb21, 1, 10, 1, 1)
        self.cb20 = QtWidgets.QCheckBox(self.groupBox)
        self.cb20.setObjectName("cb20")
        self.gridLayout_2.addWidget(self.cb20, 1, 11, 1, 1)
        self.cb19 = QtWidgets.QCheckBox(self.groupBox)
        self.cb19.setObjectName("cb19")
        self.gridLayout_2.addWidget(self.cb19, 1, 12, 1, 1)
        self.cb18 = QtWidgets.QCheckBox(self.groupBox)
        self.cb18.setObjectName("cb18")
        self.gridLayout_2.addWidget(self.cb18, 1, 13, 1, 1)
        self.cb17 = QtWidgets.QCheckBox(self.groupBox)
        self.cb17.setObjectName("cb17")
        self.gridLayout_2.addWidget(self.cb17, 1, 14, 1, 1)
        self.cb16 = QtWidgets.QCheckBox(self.groupBox)
        self.cb16.setObjectName("cb16")
        self.gridLayout_2.addWidget(self.cb16, 1, 15, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 3)
        self.labelEditValue = QtWidgets.QLabel(self.panelEditWatch)
        self.labelEditValue.setEnabled(False)
        self.labelEditValue.setWordWrap(False)
        self.labelEditValue.setObjectName("labelEditValue")
        self.gridLayout_3.addWidget(self.labelEditValue, 1, 0, 1, 1)
        self.lneEditValue = QtWidgets.QLineEdit(self.panelEditWatch)
        self.lneEditValue.setEnabled(False)
        self.lneEditValue.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lneEditValue.setObjectName("lneEditValue")
        self.gridLayout_3.addWidget(self.lneEditValue, 1, 1, 1, 1)
        self.btnApplyChanges = QtWidgets.QPushButton(self.panelEditWatch)
        self.btnApplyChanges.setAutoDefault(False)
        self.btnApplyChanges.setObjectName("btnApplyChanges")
        self.gridLayout_3.addWidget(self.btnApplyChanges, 1, 2, 1, 1)
        self.gridLayout_4.addWidget(self.panelEditWatch, 1, 0, 1, 2)

        self.retranslateUi(formWatches)
        self.btnRemoveWatch.clicked.connect(formWatches.removeWatch)
        self.btnClose.clicked.connect(formWatches.close)
        self.table.currentChanged['int','int'].connect(formWatches.clickTable)
        self.btnAddWatch.clicked.connect(formWatches.addWatch)
        self.btnApplyChanges.clicked.connect(formWatches.applyEditWatch)
        QtCore.QMetaObject.connectSlotsByName(formWatches)
        formWatches.setTabOrder(self.lneVariableName, self.lneMask)
        formWatches.setTabOrder(self.lneMask, self.btnAddWatch)
        formWatches.setTabOrder(self.btnAddWatch, self.btnRemoveWatch)
        formWatches.setTabOrder(self.btnRemoveWatch, self.btnClose)
        formWatches.setTabOrder(self.btnClose, self.table)
        formWatches.setTabOrder(self.table, self.lneEditValue)
        formWatches.setTabOrder(self.lneEditValue, self.cb0)
        formWatches.setTabOrder(self.cb0, self.cb1)
        formWatches.setTabOrder(self.cb1, self.cb2)
        formWatches.setTabOrder(self.cb2, self.cb3)
        formWatches.setTabOrder(self.cb3, self.cb4)
        formWatches.setTabOrder(self.cb4, self.cb5)
        formWatches.setTabOrder(self.cb5, self.cb6)
        formWatches.setTabOrder(self.cb6, self.cb7)
        formWatches.setTabOrder(self.cb7, self.cb8)
        formWatches.setTabOrder(self.cb8, self.cb9)
        formWatches.setTabOrder(self.cb9, self.cb10)
        formWatches.setTabOrder(self.cb10, self.cb11)
        formWatches.setTabOrder(self.cb11, self.cb12)
        formWatches.setTabOrder(self.cb12, self.cb13)
        formWatches.setTabOrder(self.cb13, self.cb14)
        formWatches.setTabOrder(self.cb14, self.cb15)
        formWatches.setTabOrder(self.cb15, self.cb16)
        formWatches.setTabOrder(self.cb16, self.cb17)
        formWatches.setTabOrder(self.cb17, self.cb18)
        formWatches.setTabOrder(self.cb18, self.cb19)
        formWatches.setTabOrder(self.cb19, self.cb20)
        formWatches.setTabOrder(self.cb20, self.cb21)
        formWatches.setTabOrder(self.cb21, self.cb22)
        formWatches.setTabOrder(self.cb22, self.cb23)
        formWatches.setTabOrder(self.cb23, self.cb24)
        formWatches.setTabOrder(self.cb24, self.cb25)
        formWatches.setTabOrder(self.cb25, self.cb26)
        formWatches.setTabOrder(self.cb26, self.cb27)
        formWatches.setTabOrder(self.cb27, self.cb28)
        formWatches.setTabOrder(self.cb28, self.cb29)
        formWatches.setTabOrder(self.cb29, self.cb30)
        formWatches.setTabOrder(self.cb30, self.cb31)

    def retranslateUi(self, formWatches):
        _translate = QtCore.QCoreApplication.translate
        formWatches.setWindowTitle(_translate("formWatches", "Watches"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("formWatches", "Variable"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("formWatches", "Description"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("formWatches", "Value"))
        self.groupBox2.setTitle(_translate("formWatches", "Add Watch"))
        self.textLabel1.setText(_translate("formWatches", "Variable:"))
        self.textLabel2.setText(_translate("formWatches", "Sec. mask:"))
        self.btnAddWatch.setText(_translate("formWatches", "Add Watch"))
        self.btnRemoveWatch.setText(_translate("formWatches", "Remove Watch"))
        self.btnClose.setText(_translate("formWatches", "Close"))
        self.panelEditWatch.setTitle(_translate("formWatches", "Edit Watch"))
        self.groupBox.setTitle(_translate("formWatches", "Bit-by-bit"))
        self.cb15.setText(_translate("formWatches", "15"))
        self.cb14.setText(_translate("formWatches", "14"))
        self.cb13.setText(_translate("formWatches", "13"))
        self.cb12.setText(_translate("formWatches", "12"))
        self.cb11.setText(_translate("formWatches", "11"))
        self.cb10.setText(_translate("formWatches", "10"))
        self.cb9.setText(_translate("formWatches", "9"))
        self.cb8.setText(_translate("formWatches", "8"))
        self.cb7.setText(_translate("formWatches", "7"))
        self.cb6.setText(_translate("formWatches", "6"))
        self.cb5.setText(_translate("formWatches", "5"))
        self.cb4.setText(_translate("formWatches", "4"))
        self.cb3.setText(_translate("formWatches", "3"))
        self.cb2.setText(_translate("formWatches", "2"))
        self.cb1.setText(_translate("formWatches", "1"))
        self.cb0.setText(_translate("formWatches", "0"))
        self.cb31.setText(_translate("formWatches", "31"))
        self.cb30.setText(_translate("formWatches", "30"))
        self.cb29.setText(_translate("formWatches", "29"))
        self.cb28.setText(_translate("formWatches", "28"))
        self.cb27.setText(_translate("formWatches", "27"))
        self.cb26.setText(_translate("formWatches", "26"))
        self.cb25.setText(_translate("formWatches", "25"))
        self.cb24.setText(_translate("formWatches", "24"))
        self.cb23.setText(_translate("formWatches", "23"))
        self.cb22.setText(_translate("formWatches", "22"))
        self.cb21.setText(_translate("formWatches", "21"))
        self.cb20.setText(_translate("formWatches", "20"))
        self.cb19.setText(_translate("formWatches", "19"))
        self.cb18.setText(_translate("formWatches", "18"))
        self.cb17.setText(_translate("formWatches", "17"))
        self.cb16.setText(_translate("formWatches", "16"))
        self.labelEditValue.setText(_translate("formWatches", "Value:"))
        self.btnApplyChanges.setText(_translate("formWatches", "Apply"))


