# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dls_pmaccontrol/formLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(314, 145)
        self.layoutWidget = QtWidgets.QWidget(Login)
        self.layoutWidget.setGeometry(QtCore.QRect(51, 11, 215, 80))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelUsername = QtWidgets.QLabel(self.layoutWidget)
        self.labelUsername.setObjectName("labelUsername")
        self.gridLayout.addWidget(self.labelUsername, 0, 0, 1, 1)
        self.lneUsername = QtWidgets.QLineEdit(self.layoutWidget)
        self.lneUsername.setText("")
        self.lneUsername.setObjectName("lneUsername")
        self.gridLayout.addWidget(self.lneUsername, 0, 1, 1, 1)
        self.labelPassword = QtWidgets.QLabel(self.layoutWidget)
        self.labelPassword.setObjectName("labelPassword")
        self.gridLayout.addWidget(self.labelPassword, 1, 0, 1, 1)
        self.lnePassword = QtWidgets.QLineEdit(self.layoutWidget)
        self.lnePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lnePassword.setObjectName("lnePassword")
        self.gridLayout.addWidget(self.lnePassword, 1, 1, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Login)
        self.layoutWidget1.setGeometry(QtCore.QRect(65, 100, 184, 38))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnCancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.btnOK = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnOK.setObjectName("btnOK")
        self.horizontalLayout.addWidget(self.btnOK)

        self.retranslateUi(Login)
        self.btnCancel.clicked.connect(Login.clickedCancel)
        self.btnOK.clicked.connect(Login.clickedOK)
        QtCore.QMetaObject.connectSlotsByName(Login)
        Login.setTabOrder(self.lneUsername, self.lnePassword)
        Login.setTabOrder(self.lnePassword, self.btnOK)
        Login.setTabOrder(self.btnOK, self.btnCancel)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "SSH Login"))
        self.labelUsername.setText(_translate("Login", "Username:"))
        self.labelPassword.setText(_translate("Login", "Password:"))
        self.btnCancel.setText(_translate("Login", "Cancel"))
        self.btnOK.setText(_translate("Login", "OK"))
