# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dls_pmaccontrol/formLogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(400, 300)
        self.lneUsername = QtWidgets.QLineEdit(Login)
        self.lneUsername.setGeometry(QtCore.QRect(170, 70, 171, 36))
        self.lneUsername.setText("")
        self.lneUsername.setObjectName("lneUsername")
        self.lnePassword = QtWidgets.QLineEdit(Login)
        self.lnePassword.setGeometry(QtCore.QRect(170, 130, 171, 36))
        self.lnePassword.setObjectName("lnePassword")
        self.labelUsername = QtWidgets.QLabel(Login)
        self.labelUsername.setGeometry(QtCore.QRect(70, 80, 81, 21))
        self.labelUsername.setObjectName("labelUsername")
        self.labelPassword = QtWidgets.QLabel(Login)
        self.labelPassword.setGeometry(QtCore.QRect(70, 140, 81, 21))
        self.labelPassword.setObjectName("labelPassword")
        self.btnCancel = QtWidgets.QPushButton(Login)
        self.btnCancel.setGeometry(QtCore.QRect(100, 220, 92, 36))
        self.btnCancel.setObjectName("btnCancel")
        self.btnOK = QtWidgets.QPushButton(Login)
        self.btnOK.setGeometry(QtCore.QRect(210, 220, 92, 36))
        self.btnOK.setObjectName("btnOK")

        self.retranslateUi(Login)
        self.btnCancel.clicked.connect(Login.clickedCancel)
        self.btnOK.clicked.connect(Login.clickedOK)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "SSH Login"))
        self.labelUsername.setText(_translate("Login", "Username:"))
        self.labelPassword.setText(_translate("Login", "Password:"))
        self.btnCancel.setText(_translate("Login", "Cancel"))
        self.btnOK.setText(_translate("Login", "OK"))
